#OBJS specifies which files to compile as part of the project
OBJS = 161044121.cpp

#CC specifies which compiler we're using
CC = g++
#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = a.out

#This is the target that compiles our executable
all :	$(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) -o $(OBJ_NAME)
	./$(OBJ_NAME)